### ISSUE TITLE
switch doesn't seem to recognize the controller  

### ISSUE THREAD

**Issue by TuTuRSiwel** [Thulinma/SwitchControllerEmulator#1]
First for context, here are the pieces of hardware i'm using :
- KeeYees Pro Micro ATmega32U4 for Arduino IDE Leonardo Bootloader (should still work right ?)
- AZDelivery Adaptator USB UART-TTL 3.3V 5V CH340G
- a pc running windows 10

1. the flashing process worked fine, i used the .hex you provided on my windows pc running the following command in my avr directory
`"bin\avrdude.exe" -C"etc\avrdude.conf" -v -patmega32u4 -cavr109 -PCOM6 -b57600 -D -Uflash:w:D:\SwitchControllerEmulator-master\Joystick.hex:imanage`
my pc then recognised the micro-controller as an HORIPAD-s as a gamepad , so all good there. 
2. installed the drivers for my serial adaptator
3. ran npm install in the project folder where index.js is located (successfully)
4. wired the microcontroller and the adaptator as instructed
5. plug the serial adaptator into my pc then the micro-controller to my switch.
nothing was detected by the switch at this point
6. ran the command `node index.js COM8` (successfully)
7. open the html page and it says that the controller is connected.

but still no connection on the switch part. Am I missing something or did I did something wrong?
i'm not even sure that the html page is passing the input ( i tried plugging both end of the device (the microcontroller and the adaptator) into my windows pc and by inspecting the HORIPAD-s i didn't saw any inputs when pressing button on the html page (then again by plugin my procontroller, the input were there but were completly glitching out. So that could mean nothing)

does your contraption still work on your end , maybe nintendo put some kind of patch in place at some point ?

EDIT : Just redid all the process but this time running on linux (ubuntu) and now it works !!! i also recompiled the .hex just in case but i dont think it was the cause of my problem.
for the people that dont have linux reading this , you can download a virtual machine and run ubuntu as a "windows application" this way

**Comment by Thulinma** [comment]
Hey there!

On the Nintendo Switch, the controller is generally not detected until you press a few buttons first. Did you try that?
Everything definitely still works for me, and I'm pretty sure Nintendo couldn't patch this out if they wanted to. (They cannot see the difference with a "real" controller any way I know of.)

Either way, glad you got it working on Linux! It _should_ also work on Windows, though. 🤔
Closing this as the "issue" is solved, but feel free to re-open or comment further if you want to. 👍

**Comment by TuTuRSiwel** [comment]
yep, tried it .i think it might be caused the windows drivers of my serial adaptator, which is strange since everything on my computer tell me the device is ok and i'm 100% positif i installed the right one.
then again it might just be windows being windows ^^
Anyway, I manage to make everything else work on linux (minus some latency issues that forced me to tweek a little bit the keypressgenerator of the ACNHpaterntool to slow down the script a bit).
The tool is great though thanks for your work !

**Comment by TuTuRSiwel** [comment]
yep, tried it .i think it might be caused the windows drivers of my serial adaptator, which is strange since everything on my computer tell me the device is ok and i'm 100% positif i installed the right one.
then again it might just be windows being windows ^^
Anyway, I manage to make everything else work on linux (minus some latency issues that forced me to tweek a little bit the keypressgenerator of the ACNHpaterntool to slow down the script a bit).
The tool is great though thanks for your work !

**Comment by Thulinma** [comment]
Glad you find it useful! Yeah, I tweaked the timing to my own machine, and wasn't sure if that timing would work for everyone. Just out of curiosity, what timing changes did you make?

**Comment by TuTuRSiwel** [comment]
> Just out of curiosity, what timing changes did you make?

I changed the "mt" variable located in ACNLPatternTool/src/libs/ACNHKeypressGenerator.js from 50 to 100 which gave me a perfect result everytime <see the attached images>

![2021113019131600_c](https://user-images.githubusercontent.com/53349052/144107547-dfd1a4e3-27f6-4999-a6e4-8daed6f4bbed.jpg)

after some further testing even lowering the mt variable back to 50 seems to give me some great results so i have no idea what happened. it might be because of my setup or part of it (virtual machine + using the front port of my computeur + having the computeur on for a long time) 

**here are some of the nightmare fuel that was created at first with the latency issue** 

**original**
![image](https://user-images.githubusercontent.com/53349052/144109839-d483ec3a-4faa-4578-9e56-3cdc7ab59057.png)

**nightmarish one**
![2021113019143800_c](https://user-images.githubusercontent.com/53349052/144107323-1a367852-06e7-477f-9c9f-4943ffcd1317.jpg)

**A tiny bit better the second time**
![2021113019154000_c](https://user-images.githubusercontent.com/53349052/144107338-792cf542-48bc-4051-a4b4-83f6db6c9f84.jpg)

**it messed up Durring the color selection process on the following one :**
**the original**
![image](https://user-images.githubusercontent.com/53349052/144108223-1f0611cc-85e7-4b3a-a7b4-a90c6eda0726.png)
**the failed attempt** 
![2021113019135900_c](https://user-images.githubusercontent.com/53349052/144107929-758800d2-8945-4460-805f-a1eccee0204d.jpg)

**Comment by Thulinma** [comment]
These are actually kinda cool 🤣. Thanks for the feedback!
